### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nerai** [AVAVT/g0tStats#1]
Nice site! You have not selected a license yet (unless I missed it). May I kindly ask you to chose one?

Background: I'm running a little Go website myself (kyudan.net) and would like to use your loading icon. I would be glad if you could grant me this permission. Attribution is natural.

**Comment by AVAVT** [comment]
Hi nerai, thanks for asking. I have updated the license.

Anyway, you're welcome to use the loading icon as you please. It's nice to know kyudan's author, I used the website before too. Great work! :+1:

**Comment by nerai** [comment]
Thank you very much! I'm humbled.
